In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a1=np.array([1,2,3,4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3],
            [4,5,6]])

In [6]:
type(a2)

numpy.ndarray

In [7]:
a2.shape

(2, 3)

In [8]:
a2.ndim

2

In [9]:
a2.dtype

dtype('int64')

In [10]:
a2.size

6

### zeros,ones,full,arange,linspace

In [11]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.full([3,5],6.7)

array([[6.7, 6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7, 6.7]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random

In [16]:
np.random.seed(0)
np.random.random([3,6])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411],
       [0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
        0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 , 0.0202184 ,
        0.83261985]])

In [17]:
np.random.normal(0,1,[3,3])

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [18]:
np.random.randint(3,6,[3,6])

array([[3, 5, 3, 3, 3, 4],
       [4, 5, 3, 3, 4, 3],
       [4, 5, 5, 3, 4, 4]], dtype=int32)

In [19]:
np.random.rand(4,4)

array([[0.09928035, 0.96980907, 0.65314004, 0.17090959],
       [0.35815217, 0.75068614, 0.60783067, 0.32504723],
       [0.03842543, 0.63427406, 0.95894927, 0.65279032],
       [0.63505887, 0.99529957, 0.58185033, 0.41436859]])

## Array Indexing & Slicing

In [20]:
x1=np.random.randint(20,size=6)

In [21]:
x1


array([ 3, 15, 13, 16, 17,  5], dtype=int32)

### Multi-dimensional array

In [22]:
x2=np.random.randint(10,size=(3,4))

In [23]:
x2

array([[9, 3, 0, 5],
       [0, 1, 2, 4],
       [2, 0, 3, 2]], dtype=int32)

In [24]:
x2[1,2]

np.int32(2)

## Slicing

In [25]:
x1


array([ 3, 15, 13, 16, 17,  5], dtype=int32)

In [26]:
x1[0:3]

array([ 3, 15, 13], dtype=int32)

In [27]:
x1[0:4:2]

array([ 3, 13], dtype=int32)

In [28]:
x2

array([[9, 3, 0, 5],
       [0, 1, 2, 4],
       [2, 0, 3, 2]], dtype=int32)

In [29]:
x2[:2,:3]

array([[9, 3, 0],
       [0, 1, 2]], dtype=int32)

## Reshaping of Arrays & Transpose

In [30]:
grid= np.arange(1,10)
grid.shape

(9,)

In [31]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
x = np.array([1,2,3])

In [33]:
x.reshape([1,3])

array([[1, 2, 3]])

In [34]:
x=np.array([[1,2],[3,4]])

In [35]:
x.T

array([[1, 3],
       [2, 4]])

### Array Concatenation and Splitting

In [36]:
x=np.array([1,2,3])
y=np.array([2,3,4])

In [37]:
np.concatenate((x,y))

array([1, 2, 3, 2, 3, 4])

In [39]:
grid=np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [42]:
#vstack
x=np.array([1,2,3])
grid=np.array([[2,3,4],[4,4,4]])

In [43]:
np.vstack((x,grid))

array([[1, 2, 3],
       [2, 3, 4],
       [4, 4, 4]])

In [44]:
# hstack
y=np.array([[99],
            [99]])
np.hstack((y,grid))

array([[99,  2,  3,  4],
       [99,  4,  4,  4]])

### Splitingarrays

In [45]:
x=np.array([1,2,3,4,5,6,7])

In [47]:
x1,x2,x3=np.split(x,[3,5])

## Broadcasting and Vectorized operations

In [49]:
a=np.arange(3)
a


array([0, 1, 2])

In [50]:
a+5

array([5, 6, 7])

In [51]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
a+b


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [53]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

### Manipulating and Comparing

In [54]:
list_number=[1,2,3]

In [55]:
ll=np.array(list_number)

In [56]:
sum(ll)

np.int64(6)

In [57]:
np.sum(ll)

np.int64(6)

In [59]:
massive_array=np.random.random(10000)
massive_array[:5]

array([0.50962438, 0.05571469, 0.45115921, 0.01998767, 0.44171092])

In [60]:
np.sum(massive_array)

np.float64(5012.84598202491)

In [61]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.57 ms ± 60.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
17.5 μs ± 435 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [62]:
np.mean(massive_array)

np.float64(0.501284598202491)

np.max(massive_array)

### Do lech chuan & Phuong sai

In [65]:
dog_height=[600,470,170,430,300]
dog_height=np.array(dog_height)

In [66]:
np.std(dog_height)

np.float64(147.32277488562318)

In [67]:
np.var(dog_height)

np.float64(21704.0)

## Sorting Arrays

In [69]:
x=np.array([2,3,4,1,3])

In [71]:
np.sort(x)

array([1, 2, 3, 3, 4])

In [72]:
np.argsort(x)

array([3, 0, 1, 4, 2])

In [74]:
np.random.seed(42)
MatA=np.random.randint(0,10,size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [75]:
np.sort(MatA,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [76]:
np.sort(MatA,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

### Linear Algebra

In [78]:
x1=np.array([[2,3,4],
             [3,4,5]])
x2=np.array([[3,4],
             [5,6],
             [6,7]])

In [79]:
x1.dot(x2)

array([[45, 54],
       [59, 71]])

In [80]:
x1@x2

array([[45, 54],
       [59, 71]])

In [81]:
x2@x1

array([[18, 25, 32],
       [28, 39, 50],
       [33, 46, 59]])